import express from 'express';
import cors from 'cors';
import multer from 'multer';
import {Queue} from 'bullmq';
import { OpenAIEmbeddings } from '@langchain/openai';
import { QdrantVectorStore } from '@langchain/qdrant';
import {OpenAI} from 'openai';
import dotenv from 'dotenv';

dotenv.config();


const client = new OpenAI({
  apiKey : process.env.OPENAI_API_KEY,
});


const queue = new Queue('file-upload-queue', {
  connection: {
    host: 'localhost',
    port: 6379
  }
});


const storage = multer.diskStorage({
    destination: function (req, file, cb) {
      cb(null, 'uploads/')
    },
    filename: function (req, file, cb) {
      const uniqueSuffix = Date.now() + '-' + Math.round(Math.random() * 1E9)
      cb(null, `${uniqueSuffix}-${file.originalname}`);
    },
  });



const upload = multer({ storage: storage })

const app = express()

app.use(cors());

app.get('/', (req,res)=>{
    return res.json({status: "All Good"})
})

app.post('/upload/pdf', upload.single('pdf'), (req, res) => {

  console.log('File uploaded to server:', req.file);

  if (!req.file) {
    console.error('No file received by server.');
    return res.status(400).json({ message: 'No file uploaded.' });
  }

  if (!req.file.filename) {
    console.error('req.file.filename is undefined on server side.');
    return res.status(500).json({ message: 'Error processing file: filename not generated.' });
  }

  // Add file info to queue for processing
  queue.add('file-ready', JSON.stringify({
    filename: req.file.originalname,
    source: req.file.destination,
    path: req.file.path
  }));

  const responsePayload = {
    message: 'File uploaded successfully!',
    fileName: req.file.filename, // This is the prefixed filename generated by multer
    fileUrl: `/uploads/${req.file.filename}`
  };

  console.log('Sending response to client:', responsePayload);
  return res.json(responsePayload);
});


// Serve the uploads folder as static files
app.use('/uploads', express.static('uploads'));

app.get ('/chat', async  (req,res)=>{
  const userQuery = req.query.message;
  const embeddings = new OpenAIEmbeddings({
          apiKey: process.env.OPENAI_API_KEY,
          modelName: "text-embedding-3-small"
          });
  const vectorStore = await QdrantVectorStore.fromExistingCollection(
    embeddings,
    {
        url: 'http://localhost:6333',
        collectionName: 'Ai_Docs',
    }
  );
  const ret = vectorStore.asRetriever({
    k: 2,
  });
  const result = await ret.invoke(userQuery);
  
  const SYSTEM_PROMPT =
  `You are a helpful assistant who answers the query based on the available context from PDF File and try to answer in point to point form  ".
  Context:  ${JSON.stringify(result )}
  `;

  const chatResult = await client.chat.completions.create({
    model: 'gpt-3.5-turbo',
    messages: [
      { role : 'system' , content : SYSTEM_PROMPT },
      { role : 'user' , content : userQuery },
    ],
});
  
  return res.json({
    message: chatResult.choices[0].message.content,
    docs: result,
  });

});



app.listen (8000, ()=>{
    console.log('Server started on port 8000');
})